main: net.tfminecraft.VFBuilders.VFBuilders
api-version: 1.20
name: VFBuilders
version: 1.0
author: Drefvelin
folia-supported: true

depend: [TLibs, VehicleFramework]

commands:
  vfbuilders:
    useage: /<command>
    description: VFBuilders Command